hydra-genetics/cnv_sv

- config/config.yaml
- workflow/rules/exomedepth.smk
- workflow/scripts/exomedepth.R
- workflow/scripts/exomedepth_filter.R
Some things added for more robust script. And change of output file names to match .smk
> fix: Exomedepth

- workflow/rules/cnvkit.smk
> fix(cnvkit): change to correct conda env file

- workflow/envs/cnvkit.yaml
> fix: Update cnvkit.yaml

- README.md
> fix: change to point to master

- .tests/integration/config.yaml
- config/config.yaml
- workflow/Snakefile
- workflow/envs/tiddit.yaml
- workflow/rules/common.smk
- workflow/rules/tiddit.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
Adding tiddit (https://github.com/SciLifeLab/TIDDIT), calling sv, getting vcf output.
> feat: Add tiddit

- README.md
> docs(README): change header to regular text

- .tests/integration/config.yaml
- config/config.yaml
- workflow/rules/common.smk
- workflow/rules/manta.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
> feat: Add manta n

- .tests/integration/config.yaml
- config/config.yaml
- workflow/Snakefile
- workflow/envs/cnvpytor.yaml
- workflow/rules/cnvpytor.smk
- workflow/rules/common.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
> feat: Add cnvpytor

- workflow/Snakefile
> chore: alphabetical order

- .github/workflows/lint.yaml
- workflow/rules/purecn.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
> feat: added rule purecn_purity_file

- .tests/integration/config.yaml
- workflow/rules/cnvkit.smk
- workflow/rules/common.smk
- workflow/rules/gatk.smk
- workflow/rules/pindel.smk
- workflow/rules/svdb.smk
- workflow/schemas/config.schema.yaml
> feat: added function that extracts purity for purecn

- workflow/rules/cnvkit.smk
- workflow/rules/common.smk
- workflow/rules/gatk.smk
> fix: tc files only in params and does not trigger purecn

- workflow/rules/common.smk
> fix: output files

- .github/workflows/compatibility.yaml
- .github/workflows/integration.yaml
- .github/workflows/lint.yaml
- .github/workflows/pycodestyle.yaml
- .github/workflows/pytest.yaml
- .github/workflows/snakemake-dry-run.yaml
> ci: update conda settings for integration action

- README.md
> chore: update with purecn documentation

- workflow/rules/purecn.smk
> fix(purecn_copy_output): add missing benchmark and params

- COMPATIBLITY.md
> docs: update compatibility file

- COMPATIBLITY.md
- workflow/rules/purecn.smk
> chore: dev to master

- .tests/integration/config.yaml
- README.md
- config/config.yaml
- workflow/Snakefile
- workflow/envs/smncopynumbercaller.yaml
- workflow/rules/common.smk
- workflow/rules/smncopynumbercaller.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
- workflow/scripts/smncopynumbercaller_manifest.py
> feat: add smncopynumbercaller

- .tests/compatibility/Snakefile
- .tests/compatibility/config.yaml
- .tests/integration/config.yaml
- config/config.yaml
- workflow/Snakefile
- workflow/envs/automap.yaml
- workflow/envs/tiddit.yaml
- workflow/rules/automap.smk
- workflow/rules/common.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
> feat: add automap

- .tests/integration/config.yaml
- workflow/rules/automap.smk
> fix: automap input and integration test

- .github/workflows/integration.yaml
- .tests/integration/config.yaml
- README.md
- workflow/envs/automap.yaml
- workflow/envs/cnvkit.yaml
- workflow/envs/cnvpytor.yaml
- workflow/envs/exomedepth.yaml
- workflow/envs/expansionhunter.yaml
- workflow/envs/gatk.yaml
- workflow/envs/manta.yaml
- workflow/envs/pindel.yaml
- workflow/envs/purecn.yaml
- workflow/envs/reviewer.yaml
- workflow/envs/reviewer_generate_locus_list.yaml
- workflow/envs/smncopynumbercaller.yaml
- workflow/envs/svdb.yaml
- workflow/envs/tiddit.yaml
- workflow/rules/automap.smk
- workflow/rules/cnvkit.smk
- workflow/rules/cnvpytor.smk
- workflow/rules/exomedepth.smk
- workflow/rules/expansionhunter.smk
- workflow/rules/gatk.smk
- workflow/rules/manta.smk
- workflow/rules/pindel.smk
- workflow/rules/purecn.smk
- workflow/rules/reviewer.smk
- workflow/rules/smncopynumbercaller.smk
- workflow/rules/svdb.smk
- workflow/rules/tiddit.smk
we will drop support for conda, since it constantly breaking even though code hasn't been updated.
> feat: remove conda support and testing

- README.md
> docs: updated output files

- COMPATIBLITY.md
- README.md
> docs: update compatibility

- README.md
> docs: update disclaimer

- workflow/rules/common.smk
- workflow/rules/exomedepth.smk
- workflow/schemas/config.schema.yaml
- workflow/scripts/exomedepth.R
> ci: exomedepth schema and inputs

- workflow/rules/automap.smk
- workflow/rules/smncopynumbercaller.smk
> docs: update message format

- workflow/rules/exomedepth.smk
> fix: change to config.get in exomedepth_call

- workflow/rules/purecn.smk
> fix: rm extra } in benchmark name

- workflow/rules/cnvpytor.smk
> fix(cnvpytor): add bam index as input

- workflow/rules/pindel.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
> fix: pindel vcf add correct samplename and contigs in header

- workflow/rules/svdb.smk
> fix(svdb): use the overlap and extra params

- .tests/integration/config.yaml
- workflow/rules/common.smk
- workflow/rules/svdb.smk
* Adds the use of priority as a param which necessitates vcf inputs being given as a param
* Add bnd_distance as a param, addressing #152
> feat: add names for the vcfs using params and add bnd_distance param

- workflow/rules/common.smk
> fix(common): set type to str for pandas dataframe

- .tests/integration/config_pacbio.yaml
> test: fix the trgt container address

- .tests/integration/config_pacbio.yaml
> test: fix container path config_pacbio.yaml

- workflow/rules/pindel.smk
> refactor: add type to samplename in pindel-vcf

- docs/softwares.md
> docs: remove rules not used

- .tests/integration/config_pacbio.yaml
- .tests/integration/samples_pacbio.tsv
- workflow/rules/common.smk
> chore: Padraicc patch 1

- .github/workflows/integration.yaml
> ci: Update to apptainer to fix issue in integration.yaml

- docs/softwares.md
- workflow/Snakefile
- workflow/rules/bgzip.smk
- workflow/rules/common.smk
- workflow/rules/tabix.smk
- workflow/schemas/config.schema.yaml
- workflow/schemas/resources.schema.yaml
- workflow/schemas/rules.schema.yaml
> feat: add tabix and bgzip for vcf output

- .tests/compatibility/config.yaml
- .tests/integration/config.yaml
- .tests/integration/config_pacbio.yaml
- config/config.yaml
- requirements.txt
> fix: update common container

- workflow/rules/bgzip.smk
> fix: change to compatible wrapper

- workflow/rules/purecn.smk
> fix: skip making hard links before copy

- .github/workflows/integration.yaml
> test: Mambaforge is depricated, use Miniforge

- workflow/rules/tiddit.smk
> fix(tiddit): add bai file as an input

- workflow/rules/jumble.smk
- workflow/schemas/rules.schema.yaml
> fix: jumble results removed prematurely

- workflow/rules/tiddit.smk
> fix(tiddit): add threads and access extras

- .github/workflows/integration.yaml
- workflow/rules/paraphase.smk
> ci: Update integration.yaml

- .github/workflows/integration.yaml
> test: install apptainer-suid

- .github/workflows/snakemake-dry-run.yaml
- .tests/integration/config_pacbio_unit_bam.yaml
- .tests/integration/units_pacbio.tsv
- workflow/rules/common.smk
- workflow/rules/hificnv.smk
- workflow/rules/paraphase.smk
- workflow/rules/pbsv.smk
- workflow/rules/sawfish.smk
- workflow/rules/trgt.smk
> refactor: access the bam path from units using wildcards

- workflow/rules/sawfish.smk
> fix(sawfish): update inputs to function

- workflow/rules/cnvkit.smk
- workflow/rules/common.smk
Changed: change normal input to function in rule cnvkit_batch.
> feat: use get_input_bam() in rule cnvkit_batch

- workflow/rules/common.smk
> fix: better handle sample.tsv without a sex column
